---
- name: "Check for conntrack_exporter binary"
  ansible.builtin.stat:
    path: "{{ conntrack_exporter_install_dir }}/conntrack_exporter"
  changed_when: false
  register: conntrack_exporter_bin

- name: "Install requirements"
  ansible.builtin.package:
    name: "{{ __conntrack_exporter_requirements }}"
    state: present
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Install tasks"
  when: not conntrack_exporter_bin.stat.exists or conntrack_exporter_force_install|bool
  block:
    - name: "Download conntrack_exporter..."
      ansible.builtin.get_url:
        url: '{{ conntrack_exporter_url }}'
        dest: '/tmp/conntrack_exporter'
        timeout: 120
        mode: '0755'

    - name: "Copy conntrack_exporter binary..."
      ansible.builtin.copy:
        src: '/tmp/conntrack_exporter'
        dest: '{{ conntrack_exporter_install_dir }}/conntrack_exporter'
        remote_src: true
        mode: '0755'

- name: "Create systemd for conntrack_exporter"
  ansible.builtin.template:
    src: 'conntrack_exporter.service.j2'
    dest: '/etc/systemd/system/conntrack_exporter.service'
    mode: '0640'
  notify: "Restart conntrack_exporter"

- name: "Enable and Start conntrack_exporter.service"
  ansible.builtin.service:
    name: conntrack_exporter
    state: started
    enabled: true
    daemon_reload: true
